package cn.gou23.shop.entity;

import cn.gou23.shop.constant.SaleStatus;
import cn.gou23.shop.constant.SourceType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemSourceEntityCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_source
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_source
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_source
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public ItemSourceEntityCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * <ul>
     * <li>title 标题</li>
     * <li>type 货源来源类型（淘宝联盟，京东联盟，1688等等）</li>
     * <li>sourceId 货源来源唯一标示，如淘宝客就是淘宝商品ID</li>
     * <li>sourceDetailUrl 货源来源的商品详情URL</li>
     * <li>itemId 店铺中的ID</li>
     * <li>saleStatus 店铺中的状态</li>
     * <li>price 店铺销售价格</li>
     * <li>purchasePrice 进货价</li>
     * <li>purchaseDiscountPrice 进货折扣价（淘宝客就是佣金）</li>
     * <li>profit 利润</li>
     * <li>shopId 店铺ID</li>
     * <li>endDate 截止日，过了这个时间就不能进货</li>
     * <li>img 图片</li>
     * <li>sourceOwner 货源所属人</li>
     * <li>myTotalSoldQuantity 本店铺销量</li>
     * <li>sourceTotalSoldQuantity 货源销量</li>
     * <li>lastNoticeDay 最后交易日</li>
     * </ul>
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(SourceType value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(SourceType value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(SourceType value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(SourceType value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(SourceType value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(SourceType value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(SourceType value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(SourceType value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<SourceType> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<SourceType> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(SourceType value1, SourceType value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(SourceType value1, SourceType value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNull() {
            addCriterion("SOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNotNull() {
            addCriterion("SOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIdEqualTo(String value) {
            addCriterion("SOURCE_ID =", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotEqualTo(String value) {
            addCriterion("SOURCE_ID <>", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThan(String value) {
            addCriterion("SOURCE_ID >", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_ID >=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThan(String value) {
            addCriterion("SOURCE_ID <", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_ID <=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLike(String value) {
            addCriterion("SOURCE_ID like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotLike(String value) {
            addCriterion("SOURCE_ID not like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdIn(List<String> values) {
            addCriterion("SOURCE_ID in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotIn(List<String> values) {
            addCriterion("SOURCE_ID not in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdBetween(String value1, String value2) {
            addCriterion("SOURCE_ID between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotBetween(String value1, String value2) {
            addCriterion("SOURCE_ID not between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlIsNull() {
            addCriterion("SOURCE_DETAIL_URL is null");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlIsNotNull() {
            addCriterion("SOURCE_DETAIL_URL is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlEqualTo(String value) {
            addCriterion("SOURCE_DETAIL_URL =", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlNotEqualTo(String value) {
            addCriterion("SOURCE_DETAIL_URL <>", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlGreaterThan(String value) {
            addCriterion("SOURCE_DETAIL_URL >", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_DETAIL_URL >=", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlLessThan(String value) {
            addCriterion("SOURCE_DETAIL_URL <", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_DETAIL_URL <=", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlLike(String value) {
            addCriterion("SOURCE_DETAIL_URL like", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlNotLike(String value) {
            addCriterion("SOURCE_DETAIL_URL not like", value, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlIn(List<String> values) {
            addCriterion("SOURCE_DETAIL_URL in", values, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlNotIn(List<String> values) {
            addCriterion("SOURCE_DETAIL_URL not in", values, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlBetween(String value1, String value2) {
            addCriterion("SOURCE_DETAIL_URL between", value1, value2, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlNotBetween(String value1, String value2) {
            addCriterion("SOURCE_DETAIL_URL not between", value1, value2, "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("ITEM_ID is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("ITEM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("ITEM_ID =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("ITEM_ID <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("ITEM_ID >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM_ID >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("ITEM_ID <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("ITEM_ID <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("ITEM_ID like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("ITEM_ID not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("ITEM_ID in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("ITEM_ID not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("ITEM_ID between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("ITEM_ID not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIsNull() {
            addCriterion("SALE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIsNotNull() {
            addCriterion("SALE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStatusEqualTo(SaleStatus value) {
            addCriterion("SALE_STATUS =", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotEqualTo(SaleStatus value) {
            addCriterion("SALE_STATUS <>", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusGreaterThan(SaleStatus value) {
            addCriterion("SALE_STATUS >", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusGreaterThanOrEqualTo(SaleStatus value) {
            addCriterion("SALE_STATUS >=", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusLessThan(SaleStatus value) {
            addCriterion("SALE_STATUS <", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusLessThanOrEqualTo(SaleStatus value) {
            addCriterion("SALE_STATUS <=", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusLike(SaleStatus value) {
            addCriterion("SALE_STATUS like", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotLike(SaleStatus value) {
            addCriterion("SALE_STATUS not like", value, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusIn(List<SaleStatus> values) {
            addCriterion("SALE_STATUS in", values, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotIn(List<SaleStatus> values) {
            addCriterion("SALE_STATUS not in", values, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusBetween(SaleStatus value1, SaleStatus value2) {
            addCriterion("SALE_STATUS between", value1, value2, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andSaleStatusNotBetween(SaleStatus value1, SaleStatus value2) {
            addCriterion("SALE_STATUS not between", value1, value2, "saleStatus");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("PRICE =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("PRICE <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("PRICE >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("PRICE <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("PRICE in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("PRICE not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNull() {
            addCriterion("PURCHASE_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNotNull() {
            addCriterion("PURCHASE_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_PRICE =", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_PRICE <>", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThan(BigDecimal value) {
            addCriterion("PURCHASE_PRICE >", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_PRICE >=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThan(BigDecimal value) {
            addCriterion("PURCHASE_PRICE <", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_PRICE <=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIn(List<BigDecimal> values) {
            addCriterion("PURCHASE_PRICE in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotIn(List<BigDecimal> values) {
            addCriterion("PURCHASE_PRICE not in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASE_PRICE between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASE_PRICE not between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceIsNull() {
            addCriterion("PURCHASE_DISCOUNT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceIsNotNull() {
            addCriterion("PURCHASE_DISCOUNT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE =", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE <>", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE >", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE >=", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceLessThan(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE <", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASE_DISCOUNT_PRICE <=", value, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceIn(List<BigDecimal> values) {
            addCriterion("PURCHASE_DISCOUNT_PRICE in", values, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceNotIn(List<BigDecimal> values) {
            addCriterion("PURCHASE_DISCOUNT_PRICE not in", values, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASE_DISCOUNT_PRICE between", value1, value2, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andPurchaseDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASE_DISCOUNT_PRICE not between", value1, value2, "purchaseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andProfitIsNull() {
            addCriterion("PROFIT is null");
            return (Criteria) this;
        }

        public Criteria andProfitIsNotNull() {
            addCriterion("PROFIT is not null");
            return (Criteria) this;
        }

        public Criteria andProfitEqualTo(BigDecimal value) {
            addCriterion("PROFIT =", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotEqualTo(BigDecimal value) {
            addCriterion("PROFIT <>", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitGreaterThan(BigDecimal value) {
            addCriterion("PROFIT >", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROFIT >=", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitLessThan(BigDecimal value) {
            addCriterion("PROFIT <", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROFIT <=", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitIn(List<BigDecimal> values) {
            addCriterion("PROFIT in", values, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotIn(List<BigDecimal> values) {
            addCriterion("PROFIT not in", values, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROFIT between", value1, value2, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROFIT not between", value1, value2, "profit");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("SHOP_ID is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("SHOP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(String value) {
            addCriterion("SHOP_ID =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(String value) {
            addCriterion("SHOP_ID <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(String value) {
            addCriterion("SHOP_ID >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(String value) {
            addCriterion("SHOP_ID >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(String value) {
            addCriterion("SHOP_ID <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(String value) {
            addCriterion("SHOP_ID <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLike(String value) {
            addCriterion("SHOP_ID like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotLike(String value) {
            addCriterion("SHOP_ID not like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<String> values) {
            addCriterion("SHOP_ID in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<String> values) {
            addCriterion("SHOP_ID not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(String value1, String value2) {
            addCriterion("SHOP_ID between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(String value1, String value2) {
            addCriterion("SHOP_ID not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("IMG is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("IMG is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("IMG =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("IMG <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("IMG >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("IMG >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("IMG <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("IMG <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("IMG like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("IMG not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("IMG in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("IMG not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("IMG between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("IMG not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerIsNull() {
            addCriterion("SOURCE_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerIsNotNull() {
            addCriterion("SOURCE_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerEqualTo(String value) {
            addCriterion("SOURCE_OWNER =", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerNotEqualTo(String value) {
            addCriterion("SOURCE_OWNER <>", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerGreaterThan(String value) {
            addCriterion("SOURCE_OWNER >", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_OWNER >=", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerLessThan(String value) {
            addCriterion("SOURCE_OWNER <", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_OWNER <=", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerLike(String value) {
            addCriterion("SOURCE_OWNER like", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerNotLike(String value) {
            addCriterion("SOURCE_OWNER not like", value, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerIn(List<String> values) {
            addCriterion("SOURCE_OWNER in", values, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerNotIn(List<String> values) {
            addCriterion("SOURCE_OWNER not in", values, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerBetween(String value1, String value2) {
            addCriterion("SOURCE_OWNER between", value1, value2, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerNotBetween(String value1, String value2) {
            addCriterion("SOURCE_OWNER not between", value1, value2, "sourceOwner");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityIsNull() {
            addCriterion("MY_TOTAL_SOLD_QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityIsNotNull() {
            addCriterion("MY_TOTAL_SOLD_QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityEqualTo(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY =", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityNotEqualTo(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY <>", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityGreaterThan(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY >", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityGreaterThanOrEqualTo(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY >=", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityLessThan(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY <", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityLessThanOrEqualTo(Long value) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY <=", value, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityIn(List<Long> values) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY in", values, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityNotIn(List<Long> values) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY not in", values, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityBetween(Long value1, Long value2) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY between", value1, value2, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andMyTotalSoldQuantityNotBetween(Long value1, Long value2) {
            addCriterion("MY_TOTAL_SOLD_QUANTITY not between", value1, value2, "myTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityIsNull() {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityIsNotNull() {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityEqualTo(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY =", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityNotEqualTo(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY <>", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityGreaterThan(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY >", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityGreaterThanOrEqualTo(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY >=", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityLessThan(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY <", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityLessThanOrEqualTo(Long value) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY <=", value, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityIn(List<Long> values) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY in", values, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityNotIn(List<Long> values) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY not in", values, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityBetween(Long value1, Long value2) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY between", value1, value2, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andSourceTotalSoldQuantityNotBetween(Long value1, Long value2) {
            addCriterion("SOURCE_TOTAL_SOLD_QUANTITY not between", value1, value2, "sourceTotalSoldQuantity");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayIsNull() {
            addCriterion("LAST_NOTICE_DAY is null");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayIsNotNull() {
            addCriterion("LAST_NOTICE_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayEqualTo(Date value) {
            addCriterion("LAST_NOTICE_DAY =", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayNotEqualTo(Date value) {
            addCriterion("LAST_NOTICE_DAY <>", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayGreaterThan(Date value) {
            addCriterion("LAST_NOTICE_DAY >", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_NOTICE_DAY >=", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayLessThan(Date value) {
            addCriterion("LAST_NOTICE_DAY <", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayLessThanOrEqualTo(Date value) {
            addCriterion("LAST_NOTICE_DAY <=", value, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayIn(List<Date> values) {
            addCriterion("LAST_NOTICE_DAY in", values, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayNotIn(List<Date> values) {
            addCriterion("LAST_NOTICE_DAY not in", values, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayBetween(Date value1, Date value2) {
            addCriterion("LAST_NOTICE_DAY between", value1, value2, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andLastNoticeDayNotBetween(Date value1, Date value2) {
            addCriterion("LAST_NOTICE_DAY not between", value1, value2, "lastNoticeDay");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(ID) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andTitleLikeInsensitive(String value) {
            addCriterion("upper(TITLE) like", value.toUpperCase(), "title");
            return (Criteria) this;
        }

        public Criteria andSourceIdLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_ID) like", value.toUpperCase(), "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceDetailUrlLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_DETAIL_URL) like", value.toUpperCase(), "sourceDetailUrl");
            return (Criteria) this;
        }

        public Criteria andItemIdLikeInsensitive(String value) {
            addCriterion("upper(ITEM_ID) like", value.toUpperCase(), "itemId");
            return (Criteria) this;
        }

        public Criteria andShopIdLikeInsensitive(String value) {
            addCriterion("upper(SHOP_ID) like", value.toUpperCase(), "shopId");
            return (Criteria) this;
        }

        public Criteria andImgLikeInsensitive(String value) {
            addCriterion("upper(IMG) like", value.toUpperCase(), "img");
            return (Criteria) this;
        }

        public Criteria andSourceOwnerLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_OWNER) like", value.toUpperCase(), "sourceOwner");
            return (Criteria) this;
        }
    }

    /**
     * <ul>
     * <li>title 标题</li>
     * <li>type 货源来源类型（淘宝联盟，京东联盟，1688等等）</li>
     * <li>sourceId 货源来源唯一标示，如淘宝客就是淘宝商品ID</li>
     * <li>sourceDetailUrl 货源来源的商品详情URL</li>
     * <li>itemId 店铺中的ID</li>
     * <li>saleStatus 店铺中的状态</li>
     * <li>price 店铺销售价格</li>
     * <li>purchasePrice 进货价</li>
     * <li>purchaseDiscountPrice 进货折扣价（淘宝客就是佣金）</li>
     * <li>profit 利润</li>
     * <li>shopId 店铺ID</li>
     * <li>endDate 截止日，过了这个时间就不能进货</li>
     * <li>img 图片</li>
     * <li>sourceOwner 货源所属人</li>
     * <li>myTotalSoldQuantity 本店铺销量</li>
     * <li>sourceTotalSoldQuantity 货源销量</li>
     * <li>lastNoticeDay 最后交易日</li>
     * </ul>
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * <ul>
     * <li>title 标题</li>
     * <li>type 货源来源类型（淘宝联盟，京东联盟，1688等等）</li>
     * <li>sourceId 货源来源唯一标示，如淘宝客就是淘宝商品ID</li>
     * <li>sourceDetailUrl 货源来源的商品详情URL</li>
     * <li>itemId 店铺中的ID</li>
     * <li>saleStatus 店铺中的状态</li>
     * <li>price 店铺销售价格</li>
     * <li>purchasePrice 进货价</li>
     * <li>purchaseDiscountPrice 进货折扣价（淘宝客就是佣金）</li>
     * <li>profit 利润</li>
     * <li>shopId 店铺ID</li>
     * <li>endDate 截止日，过了这个时间就不能进货</li>
     * <li>img 图片</li>
     * <li>sourceOwner 货源所属人</li>
     * <li>myTotalSoldQuantity 本店铺销量</li>
     * <li>sourceTotalSoldQuantity 货源销量</li>
     * <li>lastNoticeDay 最后交易日</li>
     * </ul>
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}