package cn.gou23.shop.entity;

import cn.gou23.shop.constant.SaleStatus;
import cn.gou23.shop.constant.SourceType;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ItemSourceEntity implements Serializable {
    private String id;

    /**
     * 标题
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String title;

    /**
     * 货源来源类型（淘宝联盟，京东联盟，1688等等）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private SourceType type;

    /**
     * 货源来源唯一标示，如淘宝客就是淘宝商品ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String sourceId;

    /**
     * 货源来源的商品详情URL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String sourceDetailUrl;

    /**
     * 店铺中的ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String itemId;

    /**
     * 店铺中的状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private SaleStatus saleStatus;

    /**
     * 店铺销售价格
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private BigDecimal price;

    /**
     * 进货价
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private BigDecimal purchasePrice;

    /**
     * 进货折扣价（淘宝客就是佣金）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private BigDecimal purchaseDiscountPrice;

    /**
     * 利润
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private BigDecimal profit;

    /**
     * 店铺ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String shopId;

    /**
     * 截止日，过了这个时间就不能进货
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date endDate;

    /**
     * 图片
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String img;

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String sourceOwner;

    /**
     * 本店铺销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Long myTotalSoldQuantity;

    /**
     * 货源销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Long sourceTotalSoldQuantity;

    /**
     * 最后交易日
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date lastNoticeDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_source
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 标题
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getTitle() {
        return title;
    }

    /**
     * 标题
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 货源来源类型（淘宝联盟，京东联盟，1688等等）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public SourceType getType() {
        return type;
    }

    /**
     * 货源来源类型（淘宝联盟，京东联盟，1688等等）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setType(SourceType type) {
        this.type = type;
    }

    /**
     * 货源来源唯一标示，如淘宝客就是淘宝商品ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * 货源来源唯一标示，如淘宝客就是淘宝商品ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * 货源来源的商品详情URL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getSourceDetailUrl() {
        return sourceDetailUrl;
    }

    /**
     * 货源来源的商品详情URL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSourceDetailUrl(String sourceDetailUrl) {
        this.sourceDetailUrl = sourceDetailUrl == null ? null : sourceDetailUrl.trim();
    }

    /**
     * 店铺中的ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * 店铺中的ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * 店铺中的状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public SaleStatus getSaleStatus() {
        return saleStatus;
    }

    /**
     * 店铺中的状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSaleStatus(SaleStatus saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * 店铺销售价格
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * 店铺销售价格
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * 进货价
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * 进货价
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * 进货折扣价（淘宝客就是佣金）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public BigDecimal getPurchaseDiscountPrice() {
        return purchaseDiscountPrice;
    }

    /**
     * 进货折扣价（淘宝客就是佣金）
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setPurchaseDiscountPrice(BigDecimal purchaseDiscountPrice) {
        this.purchaseDiscountPrice = purchaseDiscountPrice;
    }

    /**
     * 利润
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * 利润
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * 店铺ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * 店铺ID
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * 截止日，过了这个时间就不能进货
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * 截止日，过了这个时间就不能进货
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * 图片
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getImg() {
        return img;
    }

    /**
     * 图片
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getSourceOwner() {
        return sourceOwner;
    }

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSourceOwner(String sourceOwner) {
        this.sourceOwner = sourceOwner == null ? null : sourceOwner.trim();
    }

    /**
     * 本店铺销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Long getMyTotalSoldQuantity() {
        return myTotalSoldQuantity;
    }

    /**
     * 本店铺销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setMyTotalSoldQuantity(Long myTotalSoldQuantity) {
        this.myTotalSoldQuantity = myTotalSoldQuantity;
    }

    /**
     * 货源销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Long getSourceTotalSoldQuantity() {
        return sourceTotalSoldQuantity;
    }

    /**
     * 货源销量
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSourceTotalSoldQuantity(Long sourceTotalSoldQuantity) {
        this.sourceTotalSoldQuantity = sourceTotalSoldQuantity;
    }

    /**
     * 最后交易日
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getLastNoticeDay() {
        return lastNoticeDay;
    }

    /**
     * 最后交易日
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setLastNoticeDay(Date lastNoticeDay) {
        this.lastNoticeDay = lastNoticeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ItemSourceEntity other = (ItemSourceEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSourceId() == null ? other.getSourceId() == null : this.getSourceId().equals(other.getSourceId()))
            && (this.getSourceDetailUrl() == null ? other.getSourceDetailUrl() == null : this.getSourceDetailUrl().equals(other.getSourceDetailUrl()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getSaleStatus() == null ? other.getSaleStatus() == null : this.getSaleStatus().equals(other.getSaleStatus()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getPurchasePrice() == null ? other.getPurchasePrice() == null : this.getPurchasePrice().equals(other.getPurchasePrice()))
            && (this.getPurchaseDiscountPrice() == null ? other.getPurchaseDiscountPrice() == null : this.getPurchaseDiscountPrice().equals(other.getPurchaseDiscountPrice()))
            && (this.getProfit() == null ? other.getProfit() == null : this.getProfit().equals(other.getProfit()))
            && (this.getShopId() == null ? other.getShopId() == null : this.getShopId().equals(other.getShopId()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getImg() == null ? other.getImg() == null : this.getImg().equals(other.getImg()))
            && (this.getSourceOwner() == null ? other.getSourceOwner() == null : this.getSourceOwner().equals(other.getSourceOwner()))
            && (this.getMyTotalSoldQuantity() == null ? other.getMyTotalSoldQuantity() == null : this.getMyTotalSoldQuantity().equals(other.getMyTotalSoldQuantity()))
            && (this.getSourceTotalSoldQuantity() == null ? other.getSourceTotalSoldQuantity() == null : this.getSourceTotalSoldQuantity().equals(other.getSourceTotalSoldQuantity()))
            && (this.getLastNoticeDay() == null ? other.getLastNoticeDay() == null : this.getLastNoticeDay().equals(other.getLastNoticeDay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSourceId() == null) ? 0 : getSourceId().hashCode());
        result = prime * result + ((getSourceDetailUrl() == null) ? 0 : getSourceDetailUrl().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getSaleStatus() == null) ? 0 : getSaleStatus().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPurchasePrice() == null) ? 0 : getPurchasePrice().hashCode());
        result = prime * result + ((getPurchaseDiscountPrice() == null) ? 0 : getPurchaseDiscountPrice().hashCode());
        result = prime * result + ((getProfit() == null) ? 0 : getProfit().hashCode());
        result = prime * result + ((getShopId() == null) ? 0 : getShopId().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getImg() == null) ? 0 : getImg().hashCode());
        result = prime * result + ((getSourceOwner() == null) ? 0 : getSourceOwner().hashCode());
        result = prime * result + ((getMyTotalSoldQuantity() == null) ? 0 : getMyTotalSoldQuantity().hashCode());
        result = prime * result + ((getSourceTotalSoldQuantity() == null) ? 0 : getSourceTotalSoldQuantity().hashCode());
        result = prime * result + ((getLastNoticeDay() == null) ? 0 : getLastNoticeDay().hashCode());
        return result;
    }
}