package cn.gou23.shop.entity;

import java.io.Serializable;

public class ShopEntity implements Serializable {
    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String id;

    /**
     * 店铺名称
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String name;

    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getId() {
        return id;
    }

    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 店铺名称
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getName() {
        return name;
    }

    /**
     * 店铺名称
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * sessionkey_taobao
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopEntity other = (ShopEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSessionKey() == null ? other.getSessionKey() == null : this.getSessionKey().equals(other.getSessionKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSessionKey() == null) ? 0 : getSessionKey().hashCode());
        return result;
    }
}