package cn.gou23.shop.entity;

import cn.gou23.shop.constant.SourceType;
import java.io.Serializable;

public class SourceOwnerEntity implements Serializable {
    private String id;

    /**
     * 货源类型，如淘客，京东联盟等
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private SourceType type;

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String sourceOwner;

    /**
     * 备注
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_owner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 货源类型，如淘客，京东联盟等
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public SourceType getType() {
        return type;
    }

    /**
     * 货源类型，如淘客，京东联盟等
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setType(SourceType type) {
        this.type = type;
    }

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getSourceOwner() {
        return sourceOwner;
    }

    /**
     * 货源所属人
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSourceOwner(String sourceOwner) {
        this.sourceOwner = sourceOwner == null ? null : sourceOwner.trim();
    }

    /**
     * 备注
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_owner
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SourceOwnerEntity other = (SourceOwnerEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSourceOwner() == null ? other.getSourceOwner() == null : this.getSourceOwner().equals(other.getSourceOwner()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_owner
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSourceOwner() == null) ? 0 : getSourceOwner().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}