package cn.gou23.shop.dao;

import cn.gou23.shop.entity.ItemSourceEntity;
import cn.gou23.shop.entity.ItemSourceEntityCondition;
import cn.gou23.shop.model.ItemSourceModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ItemSourceEntityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int countByExample(ItemSourceEntityCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int deleteByExample(ItemSourceEntityCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int insert(ItemSourceEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int insertSelective(ItemSourceEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	List<ItemSourceModel> selectByExampleWithRowbounds(
			ItemSourceEntityCondition example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	List<ItemSourceModel> selectByExample(ItemSourceEntityCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	ItemSourceModel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ItemSourceEntity record,
			@Param("example") ItemSourceEntityCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ItemSourceEntity record,
			@Param("example") ItemSourceEntityCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ItemSourceEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item_source
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ItemSourceEntity record);

	/**
	 * 
	 * 描述:查询黑名单
	 * 
	 * @return
	 * @author liyixing 2015年9月5日 上午10:32:01
	 */
	List<ItemSourceModel> selectBlacklist();
	
	/**
	 * 
	 * 描述:查询货源黑名单
	 * 
	 * @return
	 * @author liyixing 2015年9月5日 上午10:32:01
	 */
	List<ItemSourceModel> selectSourceBlacklist();
}