package cn.gou23.shop.dao;

import cn.gou23.shop.entity.SourceBlacklistEntity;
import cn.gou23.shop.entity.SourceBlacklistEntityCondition;
import cn.gou23.shop.model.SourceBlacklistModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SourceBlacklistEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int countByExample(SourceBlacklistEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int deleteByExample(SourceBlacklistEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int insert(SourceBlacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int insertSelective(SourceBlacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    List<SourceBlacklistModel> selectByExampleWithRowbounds(SourceBlacklistEntityCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    List<SourceBlacklistModel> selectByExample(SourceBlacklistEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    SourceBlacklistModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SourceBlacklistEntity record, @Param("example") SourceBlacklistEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SourceBlacklistEntity record, @Param("example") SourceBlacklistEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SourceBlacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_blacklist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SourceBlacklistEntity record);
}